apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-frontend-service
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
    app: vue-frontend
